### ISSUE TITLE
Upgrade to Clojure 1.11

### ISSUE THREAD

**Issue by dexterous** [ghoseb/chainmap#1]
https://github.com/ghoseb/chainmap/blob/6f4f25f22a80a227f5a78c757eb839bd231ad42e/project.clj#L3

**Comment by ghoseb** [comment]
@dexterous does anyone even use this project? :-)

**Comment by dexterous** [comment]
I doubt it, but I was gonna use it as a spring board for a few basic exercises I was going to do. I could've sworn I created that issue in my own fork, can't figure out how it got in your repo. My bad. Feel free to close it.

**Comment by ghoseb** [comment]
#wontfix
